# -*- coding: utf-8 -*-

TOOLS = [
    {
        "id": "rbt2atp",
        "name": "RBT转ATP",
        "package": "RBT2ATP",
        "doc": "docs/rbt2atp.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "rbt_file_organization",
        "name": "RBT文件整理",
        "package": "RBT_Organization",
        "doc": "docs/rbt-organization.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "rbt_bit_converter",
        "name": "RBT/BIT互转",
        "package": "RBT_BIT_Converter",
        "doc": "docs/rbt-bit-converter.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "rbt2vcd",
        "name": "RBT转VCD",
        "package": "RBT2VCD",
        "doc": "docs/rbt2vcd.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "create_project",
        "name": "创建Vivado工程",
        "package": "Create_Project",
        "doc": "docs/create-project.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "config_board_v2",
        "name": "配置板烧写程序-V2",
        "package": "Config_Board_V2",
        "doc": "docs/config-board-v2.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "generate_ucf",
        "name": "生成UCF约束",
        "package": "GenerateUcf",
        "doc": "docs/generate-ucf.md",
        "entry": "create_widget",
        "enabled": True,
    },
]
