# -*- coding: utf-8 -*-

TOOLS = [
    {
        "id": "rbt2atp",
        "name": "RBT转ATP",
        "package": "RBT2ATP",
        "doc": "RBT2ATP/AGENT.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "rbt_file_organization",
        "name": "RBT文件整理",
        "package": "RBT_Organization",
        "doc": "RBT_Organization/AGENT.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "rbt_bit_converter",
        "name": "RBT/BIT互转",
        "package": "RBT_BIT_Converter",
        "doc": "RBT_BIT_Converter/AGENT.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "rbt2vcd",
        "name": "RBT转VCD",
        "package": "RBT2VCD",
        "doc": "RBT2VCD/AGENT.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "create_project",
        "name": "创建Vivado工程",
        "package": "Create_Project",
        "doc": "Create_Project/AGENT.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "config_board_v2",
        "name": "配置板烧写程序-V2",
        "package": "Config_Board_V2",
        "doc": "Config_Board_V2/AGENT.md",
        "entry": "create_widget",
        "enabled": True,
    },
    {
        "id": "generate_ucf",
        "name": "生成UCF约束",
        "package": "GenerateUcf",
        "doc": "GenerateUcf/AGENT.md",
        "entry": "create_widget",
        "enabled": True,
    },
]
